// 自建 IELTS Reading Academic 扩展词库
// 词条释义、同义替换与例句为本项目整理，不复制第三方教材文本。
window.__ACADEMIC_DATA__ = {
  id: "academic-reading",
  name: "IELTS 阅读扩展",
  description: "高频学术阅读词与同义替换",
  words: [
    {id:"a001",word:"abundant",pos:"adj.",synonyms:["plentiful","ample","numerous"],chinese:"丰富的；充足的",example:"The region has abundant supplies of fresh water."},
    {id:"a002",word:"acquire",pos:"v.",synonyms:["obtain","gain","get"],chinese:"获得；习得",example:"Children acquire language through repeated exposure."},
    {id:"a003",word:"adequate",pos:"adj.",synonyms:["sufficient","enough","acceptable"],chinese:"足够的；合格的",example:"The evidence was adequate to support the conclusion."},
    {id:"a004",word:"adjacent",pos:"adj.",synonyms:["nearby","neighbouring","next to"],chinese:"邻近的",example:"The species was also found in adjacent habitats."},
    {id:"a005",word:"advocate",pos:"v./n.",synonyms:["support","promote","proponent"],chinese:"提倡；支持者",example:"Many researchers advocate earlier intervention."},
    {id:"a006",word:"aggregate",pos:"v./n.",synonyms:["combine","total","collect"],chinese:"汇总；总量",example:"The figures aggregate data from several surveys."},
    {id:"a007",word:"allocate",pos:"v.",synonyms:["assign","distribute","designate"],chinese:"分配",example:"More funding was allocated to preventive care."},
    {id:"a008",word:"alter",pos:"v.",synonyms:["change","modify","adjust"],chinese:"改变",example:"Urban growth can alter local weather patterns."},
    {id:"a009",word:"ambiguous",pos:"adj.",synonyms:["unclear","vague","uncertain"],chinese:"含糊的；不明确的",example:"The wording of the question was deliberately ambiguous."},
    {id:"a010",word:"analogous",pos:"adj.",synonyms:["similar","comparable","parallel"],chinese:"类似的；可比的",example:"The process is analogous to natural selection."},
    {id:"a011",word:"anticipate",pos:"v.",synonyms:["expect","predict","foresee"],chinese:"预期；预测",example:"Researchers anticipate further growth in demand."},
    {id:"a012",word:"apparent",pos:"adj.",synonyms:["obvious","evident","seeming"],chinese:"明显的；表面上的",example:"There was an apparent decline in productivity."},
    {id:"a013",word:"arbitrary",pos:"adj.",synonyms:["random","unreasoned","subjective"],chinese:"任意的；武断的",example:"The boundary was based on an arbitrary historical decision."},
    {id:"a014",word:"attain",pos:"v.",synonyms:["achieve","reach","obtain"],chinese:"达到；获得",example:"Few participants attained the highest score."},
    {id:"a015",word:"attribute",pos:"v./n.",synonyms:["ascribe","characteristic","feature"],chinese:"归因于；属性",example:"The change was attributed to improved technology."},
    {id:"a016",word:"cease",pos:"v.",synonyms:["stop","halt","end"],chinese:"停止",example:"Production ceased after the resource was exhausted."},
    {id:"a017",word:"coherent",pos:"adj.",synonyms:["logical","consistent","unified"],chinese:"连贯的；一致的",example:"The evidence forms a coherent explanation of the pattern."},
    {id:"a018",word:"compelling",pos:"adj.",synonyms:["convincing","persuasive","forceful"],chinese:"有说服力的；强烈的",example:"The study provides compelling evidence for the theory."},
    {id:"a019",word:"comprehensive",pos:"adj.",synonyms:["complete","extensive","thorough"],chinese:"全面的",example:"A comprehensive survey was conducted across the country."},
    {id:"a020",word:"consecutive",pos:"adj.",synonyms:["successive","continuous","following"],chinese:"连续的",example:"Temperatures rose for five consecutive years."},
    {id:"a021",word:"constitute",pos:"v.",synonyms:["form","make up","comprise"],chinese:"构成",example:"Older adults constitute a growing share of the population."},
    {id:"a022",word:"controversy",pos:"n.",synonyms:["debate","dispute","disagreement"],chinese:"争议",example:"The proposal generated considerable controversy."},
    {id:"a023",word:"conventional",pos:"adj.",synonyms:["traditional","standard","usual"],chinese:"传统的；常规的",example:"The new approach outperformed conventional methods."},
    {id:"a024",word:"convert",pos:"v.",synonyms:["transform","change","turn into"],chinese:"转化；转换",example:"The device converts sunlight into electricity."},
    {id:"a025",word:"crucial",pos:"adj.",synonyms:["essential","critical","vital"],chinese:"关键的",example:"Timing is crucial to the success of the treatment."},
    {id:"a026",word:"decline",pos:"v./n.",synonyms:["decrease","fall","deteriorate"],chinese:"下降；衰退",example:"The population declined sharply after 2000."},
    {id:"a027",word:"derive",pos:"v.",synonyms:["obtain","originate","come from"],chinese:"获得；源自",example:"The material is derived from plant fibres."},
    {id:"a028",word:"diminish",pos:"v.",synonyms:["decrease","reduce","weaken"],chinese:"减少；削弱",example:"The effect diminished as the distance increased."},
    {id:"a029",word:"discrete",pos:"adj.",synonyms:["separate","distinct","individual"],chinese:"分离的；离散的",example:"The researchers divided the process into discrete stages."},
    {id:"a030",word:"displace",pos:"v.",synonyms:["replace","move","remove"],chinese:"取代；使离开",example:"Automation may displace some routine jobs."},
    {id:"a031",word:"distinct",pos:"adj.",synonyms:["different","separate","clear"],chinese:"不同的；清晰的",example:"The study identified three distinct patterns."},
    {id:"a032",word:"elicit",pos:"v.",synonyms:["produce","draw out","evoke"],chinese:"引出；诱发",example:"The images were designed to elicit an emotional response."},
    {id:"a033",word:"empirical",pos:"adj.",synonyms:["observational","evidence-based","experimental"],chinese:"实证的；经验的",example:"The hypothesis is supported by empirical evidence."},
    {id:"a034",word:"enhance",pos:"v.",synonyms:["improve","increase","strengthen"],chinese:"提高；增强",example:"Regular feedback can enhance learning outcomes."},
    {id:"a035",word:"ensure",pos:"v.",synonyms:["guarantee","make certain","secure"],chinese:"确保",example:"Several checks were used to ensure data quality."},
    {id:"a036",word:"equivalent",pos:"adj./n.",synonyms:["equal","comparable","counterpart"],chinese:"等同的；相当物",example:"The two measures are not directly equivalent."},
    {id:"a037",word:"exceed",pos:"v.",synonyms:["surpass","go beyond","outstrip"],chinese:"超过",example:"Demand is expected to exceed supply."},
    {id:"a038",word:"exclude",pos:"v.",synonyms:["omit","leave out","eliminate"],chinese:"排除；不包括",example:"Participants under eighteen were excluded from the study."},
    {id:"a039",word:"facilitate",pos:"v.",synonyms:["enable","assist","make easier"],chinese:"促进；使便利",example:"Digital tools facilitate collaboration across institutions."},
    {id:"a040",word:"fluctuate",pos:"v.",synonyms:["vary","change","oscillate"],chinese:"波动",example:"Energy prices fluctuate throughout the year."},
    {id:"a041",word:"formulate",pos:"v.",synonyms:["develop","devise","create"],chinese:"制定；构想",example:"The team formulated a new explanation for the results."},
    {id:"a042",word:"inhibit",pos:"v.",synonyms:["prevent","restrain","suppress"],chinese:"抑制；阻止",example:"Low temperatures inhibit bacterial growth."},
    {id:"a043",word:"inherent",pos:"adj.",synonyms:["intrinsic","built-in","natural"],chinese:"内在的；固有的",example:"Every measurement method has inherent limitations."},
    {id:"a044",word:"innovative",pos:"adj.",synonyms:["novel","original","new"],chinese:"创新的",example:"The project introduced an innovative recycling process."},
    {id:"a045",word:"intervene",pos:"v.",synonyms:["interfere","step in","mediate"],chinese:"干预；介入",example:"Doctors may intervene before symptoms become severe."},
    {id:"a046",word:"magnitude",pos:"n.",synonyms:["size","extent","scale"],chinese:"大小；程度",example:"The magnitude of the effect varied between regions."},
    {id:"a047",word:"mediate",pos:"v.",synonyms:["influence","intervene","connect"],chinese:"调节；居中影响",example:"Social support may mediate the impact of stress."},
    {id:"a048",word:"negligible",pos:"adj.",synonyms:["insignificant","minimal","tiny"],chinese:"可忽略的；极小的",example:"The difference between the groups was negligible."},
    {id:"a049",word:"notion",pos:"n.",synonyms:["idea","concept","belief"],chinese:"概念；观念",example:"The findings challenge the notion that ability is fixed."},
    {id:"a050",word:"persistent",pos:"adj.",synonyms:["lasting","continuous","enduring"],chinese:"持续的；顽固的",example:"Persistent drought has reduced agricultural output."},
    {id:"a051",word:"plausible",pos:"adj.",synonyms:["believable","reasonable","credible"],chinese:"看似合理的；可信的",example:"The authors offered a plausible explanation for the anomaly."},
    {id:"a052",word:"predominant",pos:"adj.",synonyms:["main","dominant","principal"],chinese:"主要的；占主导的",example:"Road transport remains the predominant source of emissions."},
    {id:"a053",word:"preliminary",pos:"adj.",synonyms:["initial","early","introductory"],chinese:"初步的",example:"Preliminary results suggest a modest improvement."},
    {id:"a054",word:"presume",pos:"v.",synonyms:["assume","suppose","believe"],chinese:"假定；推测",example:"The model presumes that other conditions remain constant."},
    {id:"a055",word:"prevalent",pos:"adj.",synonyms:["common","widespread","frequent"],chinese:"普遍的；流行的",example:"The condition is more prevalent among older adults."},
    {id:"a056",word:"profound",pos:"adj.",synonyms:["deep","significant","far-reaching"],chinese:"深刻的；巨大的",example:"The invention had a profound impact on communication."},
    {id:"a057",word:"proportion",pos:"n.",synonyms:["share","percentage","fraction"],chinese:"比例；部分",example:"A large proportion of respondents preferred online access."},
    {id:"a058",word:"random",pos:"adj.",synonyms:["arbitrary","chance","unsystematic"],chinese:"随机的",example:"Participants were assigned to groups at random."},
    {id:"a059",word:"reinforce",pos:"v.",synonyms:["strengthen","support","confirm"],chinese:"加强；强化",example:"Repeated practice reinforces long-term memory."},
    {id:"a060",word:"relatively",pos:"adv.",synonyms:["comparatively","fairly","moderately"],chinese:"相对地",example:"The technology remains relatively inexpensive."},
    {id:"a061",word:"restrict",pos:"v.",synonyms:["limit","constrain","curb"],chinese:"限制",example:"The law restricts development near protected habitats."},
    {id:"a062",word:"robust",pos:"adj.",synonyms:["strong","reliable","resilient"],chinese:"稳健的；强健的",example:"The conclusion remained robust across several analyses."},
    {id:"a063",word:"scarce",pos:"adj.",synonyms:["rare","limited","insufficient"],chinese:"稀缺的",example:"Fresh water is scarce in many arid regions."},
    {id:"a064",word:"significant",pos:"adj.",synonyms:["important","substantial","meaningful"],chinese:"显著的；重要的",example:"The intervention produced a significant reduction in risk."},
    {id:"a065",word:"simultaneous",pos:"adj.",synonyms:["concurrent","at the same time","coincident"],chinese:"同时的",example:"The system records simultaneous changes in temperature and pressure."},
    {id:"a066",word:"subsequent",pos:"adj.",synonyms:["later","following","next"],chinese:"随后的",example:"Subsequent studies failed to reproduce the original result."},
    {id:"a067",word:"substantial",pos:"adj.",synonyms:["considerable","large","significant"],chinese:"大量的；实质的",example:"The policy led to substantial savings."},
    {id:"a068",word:"sustain",pos:"v.",synonyms:["maintain","support","continue"],chinese:"维持；支撑",example:"The ecosystem cannot sustain unlimited extraction."},
    {id:"a069",word:"tentative",pos:"adj.",synonyms:["uncertain","provisional","preliminary"],chinese:"暂定的；试探性的",example:"The researchers reached a tentative conclusion."},
    {id:"a070",word:"transform",pos:"v.",synonyms:["convert","change","reshape"],chinese:"转变；改造",example:"New transport links transformed the local economy."},
    {id:"a071",word:"undergo",pos:"v.",synonyms:["experience","go through","be subjected to"],chinese:"经历；经受",example:"The samples underwent further chemical analysis."},
    {id:"a072",word:"valid",pos:"adj.",synonyms:["sound","legitimate","well-founded"],chinese:"有效的；合理的",example:"The test is valid only under controlled conditions."},
    {id:"a073",word:"variable",pos:"n./adj.",synonyms:["factor","changing","fluctuating"],chinese:"变量；可变的",example:"Age was treated as an important variable in the model."},
    {id:"a074",word:"viable",pos:"adj.",synonyms:["feasible","workable","practical"],chinese:"可行的",example:"Solar power is now a viable option for remote communities."},
    {id:"a075",word:"widespread",pos:"adj.",synonyms:["prevalent","extensive","common"],chinese:"广泛的",example:"The practice became widespread during the nineteenth century."},
    {id:"a076",word:"yield",pos:"v./n.",synonyms:["produce","output","result"],chinese:"产生；产量",example:"The new crop variety yields more food with less water."},
    {id:"a077",word:"accelerate",pos:"v.",synonyms:["speed up","hasten","increase the rate"],chinese:"加速",example:"Warmer conditions can accelerate ice loss."},
    {id:"a078",word:"conserve",pos:"v.",synonyms:["preserve","save","protect"],chinese:"保护；节约",example:"The programme encourages households to conserve water."},
    {id:"a079",word:"deplete",pos:"v.",synonyms:["exhaust","reduce","use up"],chinese:"耗尽；大量减少",example:"Intensive farming can deplete soil nutrients."},
    {id:"a080",word:"resilient",pos:"adj.",synonyms:["robust","adaptable","strong"],chinese:"有韧性的；恢复力强的",example:"Diverse ecosystems are often more resilient to disturbance."}
  ]
};
