// 雅思阅读刘洪波538考点词
// 分三组：第1组 20个核心词（90%命中率）、第2组 100个进阶词（60%命中率）、第3组 258个高分词
window.__538_DATA__ = {
  groups: [
    {
      id: 1,
      name: "第1组",
      description: "核心考点词（20个）— 命中率90%，必背",
      words: [
        { id: 1, word: "resemble", pos: "v.", synonyms: ["like", "look like", "be similar to"], chinese: "像；类似于", ieltsMeaning: "文章中描述A像B时的同义替换，常出现在类比段落" },
        { id: 2, word: "recognize", pos: "v.", synonyms: ["perceive", "acknowledge", "realize", "appreciate", "admit", "identify", "comprehend", "understand", "know"], chinese: "认出；识别；承认", ieltsMeaning: "涵盖'认出''意识到''承认'三层含义，阅读中对应多组同义替换" },
        { id: 3, word: "adjust", pos: "v.", synonyms: ["change", "modify", "shift", "alter"], chinese: "调整；改变", ieltsMeaning: "文章说change，题目用adjust，四个同义词高频互换" },
        { id: 4, word: "approach", pos: "n.", synonyms: ["method", "way"], chinese: "方法；途径", ieltsMeaning: "科技/学术类文章高频词，讨论研究方法时必考" },
        { id: 5, word: "fundamental", pos: "adj.", synonyms: ["rudimentary", "preliminary", "basic"], chinese: "基础的；根本的", ieltsMeaning: "注意rudimentary不是'粗陋的'而是'基础的'，preliminary是'初步的'" },
        { id: 6, word: "rely on", pos: "v.", synonyms: ["depend on"], chinese: "依赖；依靠", ieltsMeaning: "最简单的同义替换之一，但必考" },
        { id: 7, word: "domestic", pos: "adj.", synonyms: ["home", "local", "national"], chinese: "国内的；家庭的", ieltsMeaning: "三层含义：domestic market 国内市场 / domestic violence 家庭暴力 / domestic flight 国内航班" },
        { id: 8, word: "measure", pos: "v.", synonyms: ["calculate", "assess", "evaluate"], chinese: "测量；评估", ieltsMeaning: "科学类文章核心词，实验评估的标配动词" },
        { id: 9, word: "trait", pos: "n.", synonyms: ["characteristic", "feature", "property"], chinese: "特征；特性", ieltsMeaning: "生物/心理类文章高频词，描述物种或人格特征" },
        { id: 10, word: "coin", pos: "v.", synonyms: ["first used", "invent"], chinese: "创造（新词）", ieltsMeaning: "不是'硬币'！阅读中只考动词义：coin a term 创造术语" },
        { id: 11, word: "artificial", pos: "adj.", synonyms: ["synthetic", "man-made"], chinese: "人造的；人工的", ieltsMeaning: "科技/环境类常考，artificial intelligence / synthetic material" },
        { id: 12, word: "prompt", pos: "v.", synonyms: ["initiate", "immediately"], chinese: "促使；立即的", ieltsMeaning: "动词义'促使、引起'，形容词义'立即的'，两种词性都考" },
        { id: 13, word: "exchange", pos: "v.", synonyms: ["share", "apply A to B"], chinese: "交换；交流", ieltsMeaning: "文化/经济类常考，exchange ideas / share information" },
        { id: 14, word: "underlie", pos: "v.", synonyms: ["based on", "ground", "root"], chinese: "构成…的基础", ieltsMeaning: "学术文章核心词，the underlying cause 根本原因" },
        { id: 15, word: "ignore", pos: "v.", synonyms: ["neglect", "overlook", "underestimate"], chinese: "忽视；忽略", ieltsMeaning: "neglect强调故意忽视，overlook强调无意忽略，underestimate是低估" },
        { id: 16, word: "fertiliser", pos: "n.", synonyms: ["chemical", "toxic", "unnatural"], chinese: "化肥", ieltsMeaning: "环境/农业类常考，注意同义替换方向是'化肥→化学制品'" },
        { id: 17, word: "that*", pos: "pron.", synonyms: ["this", "it", "they", "those", "these", "such"], chinese: "那个（指代）", ieltsMeaning: "*号词：阅读中指代关系核心，this/that/these/such 全部等价" },
        { id: 18, word: "and*", pos: "conj.", synonyms: ["or", "as well as", "both...and", "not only...but also", "other than", "in addition", "besides", "on the one hand...on the other hand", "neither...nor"], chinese: "和；以及（并列）", ieltsMeaning: "*号词：并列关系全部同义，阅读中见到这些连接词意味着前后信息同等重要" },
        { id: 19, word: "rather than*", pos: "conj.", synonyms: ["but", "yet", "however", "whereas", "nonetheless", "nevertheless", "notwithstanding", "although", "though", "instead"], chinese: "而不是（转折）", ieltsMeaning: "*号词：转折关系全部同义，阅读中看到这些词意味着后面才是重点" },
        { id: 20, word: "thanks to*", pos: "conj.", synonyms: ["stem from", "derive", "owing to", "due to", "according to", "because of", "on account of", "as a result of", "leading to", "because", "since", "for", "in that", "as", "therefore", "hence"], chinese: "由于；因为（因果）", ieltsMeaning: "*号词：因果关系全部同义，阅读中看到任何因果连接词都要注意原因和结果的位置" }
      ]
    },
    {
      id: 2,
      name: "第2组",
      description: "进阶考点词（100个）— 命中率60%",
      words: [
        { id: 21, word: "diversity", pos: "n.", synonyms: ["variety", "difference"], chinese: "多样性" },
        { id: 22, word: "detect", pos: "v.", synonyms: ["find", "look for", "seek", "search"], chinese: "发现；察觉" },
        { id: 23, word: "isolate", pos: "v.", synonyms: ["inaccessible"], chinese: "隔离；孤立" },
        { id: 24, word: "avoid", pos: "v.", synonyms: ["escape", "evitable"], chinese: "避免" },
        { id: 25, word: "budget", pos: "n.", synonyms: ["fund", "financial"], chinese: "预算；资金" },
        { id: 26, word: "adapt to", pos: "v.", synonyms: ["fit", "suit"], chinese: "适应" },
        { id: 27, word: "alternative", pos: "adj./n.", synonyms: ["substitute"], chinese: "替代的；替代品" },
        { id: 28, word: "compensate", pos: "v.", synonyms: ["make up", "offset"], chinese: "补偿；弥补" },
        { id: 29, word: "component", pos: "n.", synonyms: ["proportion"], chinese: "组成部分" },
        { id: 30, word: "military", pos: "adj.", synonyms: ["weapon", "army"], chinese: "军事的" },
        { id: 31, word: "criteria", pos: "n.", synonyms: ["standard"], chinese: "标准" },
        { id: 32, word: "curriculum", pos: "n.", synonyms: ["syllabus", "course of study"], chinese: "课程" },
        { id: 33, word: "feasible", pos: "adj.", synonyms: ["realistic", "viable"], chinese: "可行的" },
        { id: 34, word: "constrain", pos: "v.", synonyms: ["stop", "control"], chinese: "限制；约束" },
        { id: 35, word: "deficiency", pos: "n.", synonyms: ["shortage", "defect", "weakness"], chinese: "缺乏；不足" },
        { id: 36, word: "supplement", pos: "v.", synonyms: ["provision"], chinese: "补充" },
        { id: 37, word: "distinguish", pos: "v.", synonyms: ["separate", "differentiate"], chinese: "区分；辨别" },
        { id: 38, word: "analyze", pos: "v.", synonyms: ["examine", "diagnose"], chinese: "分析" },
        { id: 39, word: "emphasize", pos: "v.", synonyms: ["focus on", "stress"], chinese: "强调" },
        { id: 40, word: "enormous", pos: "adj.", synonyms: ["massive", "large"], chinese: "巨大的" },
        { id: 41, word: "imitate", pos: "v.", synonyms: ["mimic", "copy"], chinese: "模仿" },
        { id: 42, word: "impair", pos: "v.", synonyms: ["damage", "diminish", "decrease"], chinese: "损害；削弱" },
        { id: 43, word: "hinder", pos: "v.", synonyms: ["impede", "prevent", "deter", "obstacle"], chinese: "阻碍" },
        { id: 44, word: "legitimate", pos: "adj.", synonyms: ["legal"], chinese: "合法的" },
        { id: 45, word: "limitation", pos: "n.", synonyms: ["restriction"], chinese: "限制" },
        { id: 46, word: "convention", pos: "n.", synonyms: ["method", "tradition"], chinese: "惯例；传统方法" },
        { id: 47, word: "demanding", pos: "adj.", synonyms: ["troublesome"], chinese: "要求高的；费力的" },
        { id: 48, word: "determine", pos: "v.", synonyms: ["decide"], chinese: "决定" },
        { id: 49, word: "accelerate", pos: "v.", synonyms: ["speed up"], chinese: "加速" },
        { id: 50, word: "ancient", pos: "adj.", synonyms: ["aged", "old"], chinese: "古老的" },
        { id: 51, word: "beneficial", pos: "adj.", synonyms: ["helpful", "advantageous", "wholesome"], chinese: "有益的" },
        { id: 52, word: "chronic", pos: "adj.", synonyms: ["lasting"], chinese: "长期的；慢性的" },
        { id: 53, word: "conscious", pos: "adj.", synonyms: ["aware", "knowing"], chinese: "有意识的" },
        { id: 54, word: "minimize", pos: "v.", synonyms: ["reduce", "lessen"], chinese: "最小化；减少" },
        { id: 55, word: "immunity", pos: "n.", synonyms: ["resistance"], chinese: "免疫力" },
        { id: 56, word: "imperative", pos: "adj.", synonyms: ["compelling", "necessary", "urgent"], chinese: "必要的；紧急的" },
        { id: 57, word: "secrete", pos: "v.", synonyms: ["discharge", "exude"], chinese: "分泌" },
        { id: 58, word: "exaggerate", pos: "v.", synonyms: ["overstate"], chinese: "夸张" },
        { id: 59, word: "transmit", pos: "v.", synonyms: ["pass", "send", "transfer"], chinese: "传输；传递" },
        { id: 60, word: "extinct", pos: "v.", synonyms: ["die out", "lost"], chinese: "灭绝" },
        { id: 61, word: "exclusive", pos: "adj.", synonyms: ["only"], chinese: "独有的；排他的" },
        { id: 62, word: "guarantee", pos: "v.", synonyms: ["assure"], chinese: "保证" },
        { id: 63, word: "inherit", pos: "v.", synonyms: ["receive"], chinese: "继承" },
        { id: 64, word: "witness", pos: "v./n.", synonyms: ["view", "see"], chinese: "目睹；目击者" },
        { id: 65, word: "magnetic", pos: "adj.", synonyms: ["attractive"], chinese: "有磁性的；有吸引力的" },
        { id: 66, word: "loss", pos: "n.", synonyms: ["waste", "gone"], chinese: "损失；消失" },
        { id: 67, word: "option", pos: "n.", synonyms: ["choice"], chinese: "选择" },
        { id: 68, word: "prefer to", pos: "v.", synonyms: ["rather"], chinese: "更喜欢" },
        { id: 69, word: "priority", pos: "n.", synonyms: ["preference", "preferential"], chinese: "优先" },
        { id: 70, word: "primary", pos: "adj.", synonyms: ["principal", "main"], chinese: "主要的" },
        { id: 71, word: "principle", pos: "n.", synonyms: ["rule"], chinese: "原则" },
        { id: 72, word: "potential", pos: "n./adj.", synonyms: ["possibility"], chinese: "潜力；可能的" },
        { id: 73, word: "quantity", pos: "n.", synonyms: ["number"], chinese: "数量" },
        { id: 74, word: "settle", pos: "v.", synonyms: ["fix", "figure out"], chinese: "解决；定居" },
        { id: 75, word: "sophisticate", pos: "v.", synonyms: ["complicate"], chinese: "使复杂；使精致" },
        { id: 76, word: "specific", pos: "adj.", synonyms: ["detailed", "particular"], chinese: "具体的" },
        { id: 77, word: "survive", pos: "v.", synonyms: ["remain"], chinese: "幸存；留存" },
        { id: 78, word: "swift", pos: "adj.", synonyms: ["quick", "rapid"], chinese: "快速的" },
        { id: 79, word: "unexpectedly", pos: "adv.", synonyms: ["surprising"], chinese: "出乎意料地" },
        { id: 80, word: "surrounding", pos: "n.", synonyms: ["setting", "environment"], chinese: "周围环境" },
        { id: 81, word: "attempt", pos: "n.", synonyms: ["try", "test"], chinese: "尝试" },
        { id: 82, word: "expertise", pos: "n.", synonyms: ["knowledge", "skill"], chinese: "专长；专业知识" },
        { id: 83, word: "faculty", pos: "n.", synonyms: ["ability"], chinese: "能力；院系" },
        { id: 84, word: "donate", pos: "v.", synonyms: ["contribute"], chinese: "捐赠；贡献" },
        { id: 85, word: "dynamics", pos: "n.", synonyms: ["energy", "force", "move"], chinese: "动力学；动态" },
        { id: 86, word: "incentive", pos: "n.", synonyms: ["motive", "stimulus"], chinese: "激励；动机" },
        { id: 87, word: "mortality", pos: "n.", synonyms: ["death"], chinese: "死亡率" },
        { id: 88, word: "peripheral", pos: "adj.", synonyms: ["unimportant", "minor"], chinese: "次要的；周边的" },
        { id: 89, word: "vicinity", pos: "n.", synonyms: ["neighbourhood", "nearby"], chinese: "附近；邻近" },
        { id: 90, word: "threaten", pos: "v.", synonyms: ["endanger", "jeopardize", "risk", "hazard"], chinese: "威胁" },
        { id: 91, word: "practice", pos: "n.", synonyms: ["method", "exercise"], chinese: "实践；方法" },
        { id: 92, word: "bacteria", pos: "n.", synonyms: ["virus", "germ", "microbe"], chinese: "细菌" },
        { id: 93, word: "be subject to", pos: "v.", synonyms: ["face"], chinese: "受…支配；面临" },
        { id: 94, word: "be liable to", pos: "v.", synonyms: ["potential"], chinese: "有…倾向；可能" },
        { id: 95, word: "innate", pos: "adj.", synonyms: ["built-in", "inborn"], chinese: "天生的；内在的" },
        { id: 96, word: "pattern", pos: "n.", synonyms: ["formation"], chinese: "模式；图案" },
        { id: 97, word: "therapy", pos: "n.", synonyms: ["treatment"], chinese: "治疗" },
        { id: 98, word: "original", pos: "adj.", synonyms: ["initial", "first"], chinese: "原始的；最初的" },
        { id: 99, word: "confidential", pos: "adj.", synonyms: ["undisclosed", "secret", "hidden"], chinese: "机密的" },
        { id: 100, word: "cognitive", pos: "adj.", synonyms: ["mental"], chinese: "认知的" },
        { id: 101, word: "comply with", pos: "v.", synonyms: ["obey"], chinese: "遵守" },
        { id: 102, word: "consult", pos: "v.", synonyms: ["ask for advice"], chinese: "咨询" },
        { id: 103, word: "superior", pos: "adj.", synonyms: ["higher", "upper"], chinese: "更优的；上级的" },
        { id: 104, word: "co-operation", pos: "n.", synonyms: ["support", "work together"], chinese: "合作" },
        { id: 105, word: "co-ordinate", pos: "v.", synonyms: ["organize", "harmonize"], chinese: "协调" },
        { id: 106, word: "differ", pos: "v.", synonyms: ["vary"], chinese: "不同" },
        { id: 107, word: "cue", pos: "n.", synonyms: ["hint", "clue"], chinese: "提示；线索" },
        { id: 108, word: "signal", pos: "n.", synonyms: ["symbol", "mark", "sign"], chinese: "信号；标志" },
        { id: 109, word: "abandon", pos: "v.", synonyms: ["quit", "give up", "forsake"], chinese: "放弃；抛弃" },
        { id: 110, word: "halt", pos: "n./v.", synonyms: ["stop", "quit"], chinese: "停止" },
        { id: 111, word: "fragile", pos: "adj.", synonyms: ["vulnerable"], chinese: "脆弱的" },
        { id: 112, word: "retain", pos: "v.", synonyms: ["maintain"], chinese: "保留；保持" },
        { id: 113, word: "vanish", pos: "v.", synonyms: ["disappear"], chinese: "消失" },
        { id: 114, word: "delivery", pos: "n.", synonyms: ["send"], chinese: "递送；交付" },
        { id: 115, word: "erode", pos: "v.", synonyms: ["rust", "damage"], chinese: "侵蚀" },
        { id: 116, word: "induce", pos: "v.", synonyms: ["cause", "lead to"], chinese: "引起；诱导" },
        { id: 117, word: "stable", pos: "adj.", synonyms: ["constant", "unchanged"], chinese: "稳定的" },
        { id: 118, word: "integrate", pos: "v.", synonyms: ["combine", "whole"], chinese: "整合" },
        { id: 119, word: "equal", pos: "adj.", synonyms: ["fair", "even"], chinese: "平等的；相等的" },
        { id: 120, word: "grant", pos: "v.", synonyms: ["offer"], chinese: "授予；给予" }
      ]
    },
    {
      id: 3,
      name: "第3组",
      description: "高分考点词（258个）— 扩展词汇量，冲击高分",
      words: [
        { id: 121, word: "accumulate", pos: "v.", synonyms: ["gather"], chinese: "积累" },
        { id: 122, word: "addictive", pos: "adj.", synonyms: ["habit"], chinese: "上瘾的" },
        { id: 123, word: "adversity", pos: "n.", synonyms: ["trouble"], chinese: "逆境；困难" },
        { id: 124, word: "aggression", pos: "n.", synonyms: ["attack"], chinese: "攻击；侵略" },
        { id: 125, word: "agreeable", pos: "adj.", synonyms: ["pleasant"], chinese: "令人愉快的" },
        { id: 126, word: "aid", pos: "n.", synonyms: ["help"], chinese: "援助；帮助" },
        { id: 127, word: "allergic", pos: "adj.", synonyms: ["irritate"], chinese: "过敏的" },
        { id: 128, word: "altitude", pos: "n.", synonyms: ["height"], chinese: "海拔；高度" },
        { id: 129, word: "application", pos: "n.", synonyms: ["utilization"], chinese: "应用" },
        { id: 130, word: "approve", pos: "v.", synonyms: ["agree"], chinese: "批准；同意" },
        { id: 131, word: "array", pos: "n.", synonyms: ["order"], chinese: "数组；排列" },
        { id: 132, word: "assign", pos: "v.", synonyms: ["allocate"], chinese: "分配" },
        { id: 133, word: "association", pos: "n.", synonyms: ["union"], chinese: "协会；关联" },
        { id: 134, word: "attitude", pos: "n.", synonyms: ["opinion"], chinese: "态度" },
        { id: 135, word: "authority", pos: "n.", synonyms: ["government"], chinese: "权威；当局" },
        { id: 136, word: "be consistent with", pos: "v.", synonyms: ["compatible"], chinese: "与…一致" },
        { id: 137, word: "bear", pos: "v.", synonyms: ["tolerate"], chinese: "忍受；承受" },
        { id: 138, word: "blight", pos: "v.", synonyms: ["destroy"], chinese: "破坏" },
        { id: 139, word: "boundary", pos: "n.", synonyms: ["barrier"], chinese: "边界" },
        { id: 140, word: "bungle", pos: "v.", synonyms: ["mishandle"], chinese: "搞砸" },
        { id: 141, word: "burden", pos: "n.", synonyms: ["load"], chinese: "负担" },
        { id: 142, word: "calamity", pos: "n.", synonyms: ["disaster"], chinese: "灾难" },
        { id: 143, word: "capacity", pos: "n.", synonyms: ["volume"], chinese: "容量；能力" },
        { id: 144, word: "catastrophic", pos: "adj.", synonyms: ["disastrous"], chinese: "灾难性的" },
        { id: 145, word: "cater", pos: "v.", synonyms: ["serve"], chinese: "提供服务；迎合" },
        { id: 146, word: "certify", pos: "v.", synonyms: ["verify"], chinese: "认证；证明" },
        { id: 147, word: "civic", pos: "adj.", synonyms: ["municipal"], chinese: "市的；公民的" },
        { id: 148, word: "comment", pos: "n./v.", synonyms: ["remark"], chinese: "评论" },
        { id: 149, word: "commitment", pos: "n.", synonyms: ["engagement"], chinese: "承诺；投入" },
        { id: 150, word: "communal", pos: "adj.", synonyms: ["public"], chinese: "公共的；社区的" },
        { id: 151, word: "commute", pos: "v.", synonyms: ["travel"], chinese: "通勤" },
        { id: 152, word: "compare", pos: "v.", synonyms: ["contrast"], chinese: "比较；对比" },
        { id: 153, word: "conceal", pos: "v.", synonyms: ["hide"], chinese: "隐藏" },
        { id: 154, word: "concentrate", pos: "v.", synonyms: ["focus"], chinese: "集中" },
        { id: 155, word: "concur", pos: "v.", synonyms: ["agree"], chinese: "同意；一致" },
        { id: 156, word: "confer", pos: "v.", synonyms: ["grant"], chinese: "授予；协商" },
        { id: 157, word: "conflict", pos: "n.", synonyms: ["unharmonious"], chinese: "冲突" },
        { id: 158, word: "confuse", pos: "v.", synonyms: ["puzzle"], chinese: "使困惑" },
        { id: 159, word: "conservative", pos: "adj.", synonyms: ["traditional"], chinese: "保守的；传统的" },
        { id: 160, word: "considerable", pos: "adj.", synonyms: ["significant"], chinese: "相当大的" },
        { id: 161, word: "contingent", pos: "adj.", synonyms: ["uncertain"], chinese: "视情况而定的" },
        { id: 162, word: "controversial", pos: "adj.", synonyms: ["disputable"], chinese: "有争议的" },
        { id: 163, word: "correlation", pos: "n.", synonyms: ["link"], chinese: "相关性" },
        { id: 164, word: "courtship", pos: "n.", synonyms: ["mate"], chinese: "求偶；追求" },
        { id: 165, word: "crash", pos: "n.", synonyms: ["collapse"], chinese: "崩溃；坠毁" },
        { id: 166, word: "credibility", pos: "n.", synonyms: ["reliance"], chinese: "可信度" },
        { id: 167, word: "criminal", pos: "n.", synonyms: ["conviction"], chinese: "罪犯；刑事的" },
        { id: 168, word: "crisis", pos: "n.", synonyms: ["risk"], chinese: "危机" },
        { id: 169, word: "criticism", pos: "n.", synonyms: ["condemn"], chinese: "批评" },
        { id: 170, word: "curb", pos: "v.", synonyms: ["restrict"], chinese: "限制" },
        { id: 171, word: "damp", pos: "adj.", synonyms: ["wet"], chinese: "潮湿的" },
        { id: 172, word: "dazzle", pos: "v.", synonyms: ["flash"], chinese: "使目眩；使惊叹" },
        { id: 173, word: "deadline", pos: "n.", synonyms: ["limit"], chinese: "截止日期" },
        { id: 174, word: "delay", pos: "n.", synonyms: ["postpone"], chinese: "延迟" },
        { id: 175, word: "democratic", pos: "adj.", synonyms: ["republic"], chinese: "民主的" },
        { id: 176, word: "demographic", pos: "adj.", synonyms: ["population statistic"], chinese: "人口统计的" },
        { id: 177, word: "dental", pos: "adj.", synonyms: ["teeth"], chinese: "牙齿的" },
        { id: 178, word: "depression", pos: "n.", synonyms: ["frustration"], chinese: "抑郁；萧条" },
        { id: 179, word: "designate", pos: "v.", synonyms: ["appoint"], chinese: "指定；任命" },
        { id: 180, word: "detain", pos: "v.", synonyms: ["hold"], chinese: "拘留；扣留" },
        { id: 181, word: "devastate", pos: "v.", synonyms: ["wreck"], chinese: "摧毁" },
        { id: 182, word: "disclose", pos: "v.", synonyms: ["expose"], chinese: "揭露" },
        { id: 183, word: "disparate", pos: "adj.", synonyms: ["different"], chinese: "迥然不同的" },
        { id: 184, word: "display", pos: "n.", synonyms: ["show"], chinese: "展示" },
        { id: 185, word: "disrupt", pos: "v.", synonyms: ["destroy"], chinese: "扰乱；破坏" },
        { id: 186, word: "distract", pos: "v.", synonyms: ["divert"], chinese: "使分心" },
        { id: 187, word: "distribute", pos: "v.", synonyms: ["spread"], chinese: "分配；散布" },
        { id: 188, word: "documentation", pos: "n.", synonyms: ["record"], chinese: "文档；记录" },
        { id: 189, word: "domain", pos: "n.", synonyms: ["field"], chinese: "领域" },
        { id: 190, word: "dominant", pos: "adj.", synonyms: ["overbearing"], chinese: "主导的" },
        { id: 191, word: "dramatic", pos: "adj.", synonyms: ["striking"], chinese: "戏剧性的；显著的" },
        { id: 192, word: "drought", pos: "n.", synonyms: ["dry"], chinese: "干旱" },
        { id: 193, word: "durable", pos: "adj.", synonyms: ["lasting"], chinese: "耐用的；持久的" },
        { id: 194, word: "eco-friendly", pos: "adj.", synonyms: ["environmentally-friendly"], chinese: "环保的" },
        { id: 195, word: "elaborate", pos: "v.", synonyms: ["illustrate"], chinese: "详细阐述" },
        { id: 196, word: "elderly", pos: "adj.", synonyms: ["aged"], chinese: "年老的" },
        { id: 197, word: "eliminate", pos: "v.", synonyms: ["dispose"], chinese: "消除" },
        { id: 198, word: "elusive", pos: "adj.", synonyms: ["hard"], chinese: "难捉摸的；难懂的" },
        { id: 199, word: "encyclopaedia", pos: "n.", synonyms: ["entire range of knowledge"], chinese: "百科全书" },
        { id: 200, word: "entrepreneur", pos: "n.", synonyms: ["boss"], chinese: "企业家" },
        { id: 201, word: "equator", pos: "n.", synonyms: ["geography"], chinese: "赤道" },
        { id: 202, word: "erratically", pos: "adv.", synonyms: ["unpredictably"], chinese: "不规律地" },
        { id: 203, word: "established", pos: "adj.", synonyms: ["built"], chinese: "已建立的" },
        { id: 204, word: "estate", pos: "n.", synonyms: ["property"], chinese: "房产；庄园" },
        { id: 205, word: "ethical", pos: "adj.", synonyms: ["moral"], chinese: "伦理的；道德的" },
        { id: 206, word: "eventually", pos: "adv.", synonyms: ["finally"], chinese: "最终" },
        { id: 207, word: "evidence", pos: "n.", synonyms: ["proof"], chinese: "证据" },
        { id: 208, word: "evolve", pos: "v.", synonyms: ["develop"], chinese: "进化；发展" },
        { id: 209, word: "exceptional", pos: "adj.", synonyms: ["extreme", "utmost"], chinese: "例外的；杰出的" },
        { id: 210, word: "exhausted", pos: "adj.", synonyms: ["fatigue"], chinese: "筋疲力尽的" },
        { id: 211, word: "experiment", pos: "n.", synonyms: ["test"], chinese: "实验" },
        { id: 212, word: "explicit", pos: "adj.", synonyms: ["clear"], chinese: "明确的" },
        { id: 213, word: "exploit", pos: "v.", synonyms: ["use"], chinese: "利用；开发" },
        { id: 214, word: "extend", pos: "v.", synonyms: ["expand"], chinese: "延伸；扩展" },
        { id: 215, word: "extract", pos: "n./v.", synonyms: ["quotation"], chinese: "摘录；提取" },
        { id: 216, word: "famine", pos: "n.", synonyms: ["hunger"], chinese: "饥荒" },
        { id: 217, word: "finite", pos: "adj.", synonyms: ["limited"], chinese: "有限的" },
        { id: 218, word: "fitness", pos: "n.", synonyms: ["health"], chinese: "健康；健身" },
        { id: 219, word: "foe", pos: "n.", synonyms: ["enemy"], chinese: "敌人" },
        { id: 220, word: "format", pos: "n.", synonyms: ["structure"], chinese: "格式" },
        { id: 221, word: "fragment", pos: "n.", synonyms: ["piece"], chinese: "碎片" },
        { id: 222, word: "freeze", pos: "n.", synonyms: ["chill"], chinese: "冻结；极冷" },
        { id: 223, word: "fulfill", pos: "v.", synonyms: ["execute"], chinese: "履行；完成" },
        { id: 224, word: "gene", pos: "n.", synonyms: ["factor"], chinese: "基因" },
        { id: 225, word: "gifted", pos: "adj.", synonyms: ["talented"], chinese: "有天赋的" },
        { id: 226, word: "graphic", pos: "adj.", synonyms: ["picture"], chinese: "图画的；生动的" },
        { id: 227, word: "habitat", pos: "n.", synonyms: ["residence"], chinese: "栖息地" },
        { id: 228, word: "harbour", pos: "v./n.", synonyms: ["hold"], chinese: "怀有；港口" },
        { id: 229, word: "hardship", pos: "n.", synonyms: ["difficult"], chinese: "艰难" },
        { id: 230, word: "harsh", pos: "adj.", synonyms: ["rough"], chinese: "严酷的；粗糙的" },
        { id: 231, word: "hypothesis", pos: "n.", synonyms: ["assumption"], chinese: "假设" },
        { id: 232, word: "impact", pos: "n.", synonyms: ["influence"], chinese: "影响；冲击" },
        { id: 233, word: "impressive", pos: "adj.", synonyms: ["touching"], chinese: "令人印象深刻的" },
        { id: 234, word: "in accordance with", pos: "prep.", synonyms: ["conform"], chinese: "按照；依据" },
        { id: 235, word: "inaccurate", pos: "adj.", synonyms: ["incorrect"], chinese: "不准确的" },
        { id: 236, word: "inactive", pos: "adj.", synonyms: ["passive"], chinese: "不活跃的" },
        { id: 237, word: "inappropriate", pos: "adj.", synonyms: ["hard"], chinese: "不合适的" },
        { id: 238, word: "indulge", pos: "v.", synonyms: ["spoil"], chinese: "沉溺；放纵" },
        { id: 239, word: "infest", pos: "v.", synonyms: ["plague"], chinese: "侵扰；遍布" },
        { id: 240, word: "installment", pos: "n.", synonyms: ["payment on its completion"], chinese: "分期付款" },
        { id: 241, word: "intelligence", pos: "n.", synonyms: ["mind"], chinese: "智力；情报" },
        { id: 242, word: "intense", pos: "adj.", synonyms: ["strong"], chinese: "强烈的" },
        { id: 243, word: "interaction", pos: "n.", synonyms: ["social activities"], chinese: "互动" },
        { id: 244, word: "interference", pos: "n.", synonyms: ["interdependence"], chinese: "干扰" },
        { id: 245, word: "interior", pos: "n./adj.", synonyms: ["inner"], chinese: "内部；内部的" },
        { id: 246, word: "interrupt", pos: "v.", synonyms: ["stop"], chinese: "打断" },
        { id: 247, word: "introverted", pos: "adj.", synonyms: ["shyness"], chinese: "内向的" },
        { id: 248, word: "involve", pos: "v.", synonyms: ["associate"], chinese: "涉及；包含" },
        { id: 249, word: "keen", pos: "adj.", synonyms: ["strong"], chinese: "热衷的；强烈的" },
        { id: 250, word: "label", pos: "v.", synonyms: ["display"], chinese: "标记；贴标签" },
        { id: 251, word: "lack", pos: "v.", synonyms: ["shortage"], chinese: "缺乏" },
        { id: 252, word: "landscape", pos: "n.", synonyms: ["scene"], chinese: "风景；景观" },
        { id: 253, word: "likelihood", pos: "n.", synonyms: ["chance"], chinese: "可能性" },
        { id: 254, word: "limb", pos: "n.", synonyms: ["arm or leg"], chinese: "肢体" },
        { id: 255, word: "linguistic", pos: "adj.", synonyms: ["language"], chinese: "语言的" },
        { id: 256, word: "log", pos: "v./n.", synonyms: ["record"], chinese: "记录；日志" },
        { id: 257, word: "look-in", pos: "n.", synonyms: ["opportunity", "chance"], chinese: "机会" },
        { id: 258, word: "lopsided", pos: "adj.", synonyms: ["uneven"], chinese: "不平衡的" },
        { id: 259, word: "mainly", pos: "adv.", synonyms: ["primarily"], chinese: "主要地" },
        { id: 260, word: "malfunction", pos: "v.", synonyms: ["breakdown"], chinese: "故障" },
        { id: 261, word: "mammal", pos: "n.", synonyms: ["creature"], chinese: "哺乳动物" },
        { id: 262, word: "manage to do", pos: "v.", synonyms: ["success"], chinese: "设法做到" },
        { id: 263, word: "manifest", pos: "v.", synonyms: ["obvious"], chinese: "表明；明显的" },
        { id: 264, word: "manufacture", pos: "n.", synonyms: ["produce"], chinese: "制造" },
        { id: 265, word: "marine", pos: "adj.", synonyms: ["sea"], chinese: "海洋的" },
        { id: 266, word: "mate", pos: "n.", synonyms: ["spouse"], chinese: "伴侣" },
        { id: 267, word: "mechanism", pos: "n.", synonyms: ["method"], chinese: "机制；方法" },
        { id: 268, word: "mental", pos: "adj.", synonyms: ["intelligent"], chinese: "精神的；智力的" },
        { id: 269, word: "mercury", pos: "n.", synonyms: ["liquid metal"], chinese: "水银；汞" },
        { id: 270, word: "meteorological", pos: "adj.", synonyms: ["weather"], chinese: "气象的" },
        { id: 271, word: "migrate", pos: "v.", synonyms: ["move"], chinese: "迁移" },
        { id: 272, word: "moisture", pos: "n.", synonyms: ["humidity"], chinese: "水分；湿度" },
        { id: 273, word: "monitor", pos: "v.", synonyms: ["surveillance"], chinese: "监控" },
        { id: 274, word: "motif", pos: "n.", synonyms: ["theme"], chinese: "主题；图案" },
        { id: 275, word: "mould", pos: "v.", synonyms: ["form"], chinese: "塑造；模具" },
        { id: 276, word: "native", pos: "adj.", synonyms: ["original"], chinese: "本地的；本土的" },
        { id: 277, word: "nocturnal", pos: "adj.", synonyms: ["night"], chinese: "夜间活动的" },
        { id: 278, word: "norm", pos: "n.", synonyms: ["regulation"], chinese: "规范" },
        { id: 279, word: "notoriety", pos: "n.", synonyms: ["famous"], chinese: "恶名；名声" },
        { id: 280, word: "objective", pos: "n./adj.", synonyms: ["goal"], chinese: "目标；客观的" },
        { id: 281, word: "obligation", pos: "n.", synonyms: ["responsibility"], chinese: "义务；责任" },
        { id: 282, word: "obscure", pos: "v.", synonyms: ["hide"], chinese: "使模糊；隐藏" },
        { id: 283, word: "obtain", pos: "v.", synonyms: ["get"], chinese: "获得" },
        { id: 284, word: "odd", pos: "adj.", synonyms: ["strange"], chinese: "奇怪的" },
        { id: 285, word: "odour", pos: "n.", synonyms: ["smell"], chinese: "气味" },
        { id: 286, word: "offensive", pos: "adj.", synonyms: ["hostile"], chinese: "冒犯的；攻击性的" },
        { id: 287, word: "official", pos: "n./adj.", synonyms: ["authority"], chinese: "官员；官方的" },
        { id: 288, word: "optimum", pos: "n.", synonyms: ["best"], chinese: "最佳" },
        { id: 289, word: "ordinary", pos: "adj.", synonyms: ["common"], chinese: "普通的" },
        { id: 290, word: "organ", pos: "n.", synonyms: ["a part of a body"], chinese: "器官" },
        { id: 291, word: "out of the question", pos: "adj.", synonyms: ["impossible"], chinese: "不可能的" },
        { id: 292, word: "overcome", pos: "v.", synonyms: ["defeat"], chinese: "克服" },
        { id: 293, word: "overtake", pos: "v.", synonyms: ["surpass"], chinese: "超过" },
        { id: 294, word: "paralyse", pos: "v.", synonyms: ["cannot move"], chinese: "使瘫痪" },
        { id: 295, word: "paramount", pos: "adj.", synonyms: ["principal"], chinese: "最重要的" },
        { id: 296, word: "participate", pos: "v.", synonyms: ["join"], chinese: "参与" },
        { id: 297, word: "patient", pos: "adj.", synonyms: ["repetitive"], chinese: "耐心的；患者" },
        { id: 298, word: "peak", pos: "n.", synonyms: ["top"], chinese: "顶峰" },
        { id: 299, word: "permit", pos: "n.", synonyms: ["allow"], chinese: "许可；允许" },
        { id: 300, word: "persuade", pos: "v.", synonyms: ["influence"], chinese: "说服" },
        { id: 301, word: "pessimistic", pos: "adj.", synonyms: ["negative"], chinese: "悲观的" },
        { id: 302, word: "phase", pos: "n.", synonyms: ["process"], chinese: "阶段" },
        { id: 303, word: "physical", pos: "adj.", synonyms: ["body"], chinese: "身体的；物理的" },
        { id: 304, word: "plagiarise", pos: "v.", synonyms: ["copy"], chinese: "抄袭" },
        { id: 305, word: "plenty of", pos: "adj.", synonyms: ["many"], chinese: "大量的" },
        { id: 306, word: "plot", pos: "v.", synonyms: ["plan"], chinese: "密谋；情节" },
        { id: 307, word: "pose", pos: "v.", synonyms: ["cause"], chinese: "造成；摆姿势" },
        { id: 308, word: "portable", pos: "adj.", synonyms: ["conveyable"], chinese: "便携的" },
        { id: 309, word: "poverty", pos: "n.", synonyms: ["poor"], chinese: "贫困" },
        { id: 310, word: "praise", pos: "n.", synonyms: ["commend"], chinese: "表扬" },
        { id: 311, word: "predict", pos: "v.", synonyms: ["expect"], chinese: "预测" },
        { id: 312, word: "pressing", pos: "adj.", synonyms: ["urgent"], chinese: "紧迫的" },
        { id: 313, word: "private", pos: "adj.", synonyms: ["personal"], chinese: "私人的" },
        { id: 314, word: "prohibit", pos: "v.", synonyms: ["not allowed"], chinese: "禁止" },
        { id: 315, word: "prolong", pos: "v.", synonyms: ["extend"], chinese: "延长" },
        { id: 316, word: "promote", pos: "v.", synonyms: ["improve"], chinese: "促进；提升" },
        { id: 317, word: "prosper", pos: "v.", synonyms: ["success"], chinese: "繁荣" },
        { id: 318, word: "purify", pos: "v.", synonyms: ["clean"], chinese: "净化" },
        { id: 319, word: "qualify", pos: "v.", synonyms: ["fulfill"], chinese: "使合格" },
        { id: 320, word: "radical", pos: "adj.", synonyms: ["utmost"], chinese: "激进的；根本的" },
        { id: 321, word: "range", pos: "n.", synonyms: ["scope"], chinese: "范围" },
        { id: 322, word: "rare", pos: "adj.", synonyms: ["unusual"], chinese: "稀有的" },
        { id: 323, word: "rate", pos: "n./v.", synonyms: ["rank", "measure"], chinese: "比率；评级" },
        { id: 324, word: "react", pos: "v.", synonyms: ["respond"], chinese: "反应" },
        { id: 325, word: "recreation", pos: "n.", synonyms: ["entertainment"], chinese: "娱乐；消遣" },
        { id: 326, word: "reduction", pos: "n.", synonyms: ["decrease"], chinese: "减少" },
        { id: 327, word: "refer to", pos: "v.", synonyms: ["talk about"], chinese: "提及；参考" },
        { id: 328, word: "rehearsal", pos: "n.", synonyms: ["preparation"], chinese: "排练" },
        { id: 329, word: "reject", pos: "v.", synonyms: ["exclude"], chinese: "拒绝；排斥" },
        { id: 330, word: "relevant", pos: "adj.", synonyms: ["relative"], chinese: "相关的" },
        { id: 331, word: "religious", pos: "adj.", synonyms: ["sacred"], chinese: "宗教的" },
        { id: 332, word: "reluctant", pos: "adj.", synonyms: ["unwilling"], chinese: "不情愿的" },
        { id: 333, word: "reproduce", pos: "v.", synonyms: ["breed"], chinese: "繁殖；复制" },
        { id: 334, word: "responsible", pos: "adj.", synonyms: ["liable"], chinese: "负责的" },
        { id: 335, word: "revision", pos: "n.", synonyms: ["editing"], chinese: "修订；复习" },
        { id: 336, word: "revive", pos: "v.", synonyms: ["renaissance"], chinese: "复兴；苏醒" },
        { id: 337, word: "ruin", pos: "v.", synonyms: ["destroy"], chinese: "毁灭" },
        { id: 338, word: "scenic", pos: "adj.", synonyms: ["beautiful"], chinese: "风景优美的" },
        { id: 339, word: "shade", pos: "n.", synonyms: ["shelter"], chinese: "阴凉处；遮蔽" },
        { id: 340, word: "skepticism", pos: "n.", synonyms: ["doubt"], chinese: "怀疑" },
        { id: 341, word: "soar", pos: "v.", synonyms: ["increase"], chinese: "飙升" },
        { id: 342, word: "solely", pos: "adv.", synonyms: ["alone"], chinese: "仅仅；唯一地" },
        { id: 343, word: "solicitor", pos: "n.", synonyms: ["lawyer"], chinese: "律师" },
        { id: 344, word: "steer", pos: "v.", synonyms: ["manage"], chinese: "引导；驾驶" },
        { id: 345, word: "stimulate", pos: "v.", synonyms: ["motivate"], chinese: "刺激；激励" },
        { id: 346, word: "stride", pos: "n.", synonyms: ["progress"], chinese: "大步；进展" },
        { id: 347, word: "succumb", pos: "vi.", synonyms: ["yield"], chinese: "屈服" },
        { id: 348, word: "subdivide", pos: "v.", synonyms: ["break down"], chinese: "再分；细分" },
        { id: 349, word: "subtle", pos: "adj.", synonyms: ["delicate"], chinese: "微妙的" },
        { id: 350, word: "substance", pos: "n.", synonyms: ["matter"], chinese: "物质；实质" },
        { id: 351, word: "sufficiency", pos: "n.", synonyms: ["enough"], chinese: "充足" },
        { id: 352, word: "supersede", pos: "v.", synonyms: ["replace"], chinese: "取代" },
        { id: 353, word: "suppress", pos: "v.", synonyms: ["hold"], chinese: "压制；抑制" },
        { id: 354, word: "supremacy", pos: "n.", synonyms: ["priority"], chinese: "至高无上；霸权" },
        { id: 355, word: "suspicious", pos: "adj.", synonyms: ["odd"], chinese: "可疑的" },
        { id: 356, word: "sustainable", pos: "adj.", synonyms: ["long-term"], chinese: "可持续的" },
        { id: 357, word: "symptom", pos: "n.", synonyms: ["sign"], chinese: "症状" },
        { id: 358, word: "tension", pos: "n.", synonyms: ["upset"], chinese: "紧张；张力" },
        { id: 359, word: "term", pos: "n.", synonyms: ["word"], chinese: "术语；学期" },
        { id: 360, word: "throughout", pos: "adv./prep.", synonyms: ["anywhere"], chinese: "贯穿；到处" },
        { id: 361, word: "toll", pos: "n.", synonyms: ["charge"], chinese: "通行费；代价" },
        { id: 362, word: "trace", pos: "n.", synonyms: ["track"], chinese: "踪迹；追踪" },
        { id: 363, word: "transcend", pos: "v.", synonyms: ["excel"], chinese: "超越" },
        { id: 364, word: "transit", pos: "n.", synonyms: ["send"], chinese: "运输；中转" },
        { id: 365, word: "tremendous", pos: "adj.", synonyms: ["vast"], chinese: "巨大的" },
        { id: 366, word: "trigger", pos: "n.", synonyms: ["begin"], chinese: "触发；扳机" },
        { id: 367, word: "tropical", pos: "adj.", synonyms: ["hot"], chinese: "热带的" },
        { id: 368, word: "unbiased", pos: "adj.", synonyms: ["fair"], chinese: "公正的" },
        { id: 369, word: "uniform", pos: "adj.", synonyms: ["consistent"], chinese: "统一的；一致的" },
        { id: 370, word: "valuable", pos: "adj.", synonyms: ["benefit"], chinese: "有价值的" },
        { id: 371, word: "versatile", pos: "adj.", synonyms: ["all-around"], chinese: "多才多艺的；多功能的" },
        { id: 372, word: "view", pos: "v.", synonyms: ["overlook"], chinese: "看待；风景" },
        { id: 373, word: "violent", pos: "adj.", synonyms: ["fierce"], chinese: "暴力的；猛烈的" },
        { id: 374, word: "visible", pos: "adj.", synonyms: ["see"], chinese: "可见的" },
        { id: 375, word: "visual", pos: "adj.", synonyms: ["image"], chinese: "视觉的" },
        { id: 376, word: "well-being", pos: "n.", synonyms: ["health"], chinese: "幸福；健康" },
        { id: 377, word: "apply to", pos: "v.", synonyms: ["use", "utilize", "employ"], chinese: "应用于；适用于", ieltsMeaning: "exchange 的同义替换词，apply A to B = 把A应用于B" },
        { id: 378, word: "similar", pos: "adj.", synonyms: ["like", "resemble", "look like"], chinese: "相似的；类似的", ieltsMeaning: "resemble 的同义替换词，be similar to = 与…相似" }
      ]
    }
  ]
};
