// GRE Prep starter data. Vocabulary is an independently curated study list; practice questions are original.
window.__GRE_DATA__ = (() => {
  const rawWords = [
    ["abate","减弱；缓和",["lessen","subside"],1],["aberrant","异常的；偏离常规的",["anomalous","deviant"],2],["abjure","郑重放弃；发誓摒弃",["renounce","forswear"],3],["acerbic","尖刻的；酸涩的",["caustic","biting"],2],["acumen","敏锐；洞察力",["insight","shrewdness"],1],
    ["adroit","熟练的；机敏的",["skillful","dexterous"],1],["alacrity","欣然；敏捷",["eagerness","readiness"],2],["ambivalent","矛盾的；摇摆不定的",["conflicted","uncertain"],1],["ameliorate","改善；缓和",["improve","mitigate"],1],["anachronistic","时代错置的；过时的",["outdated","chronologically misplaced"],2],
    ["anomaly","异常；反常事物",["irregularity","deviation"],1],["antipathy","强烈反感",["aversion","hostility"],2],["apocryphal","真实性可疑的；杜撰的",["dubious","spurious"],2],["appease","安抚；平息",["pacify","placate"],1],["arcane","神秘难懂的；少为人知的",["esoteric","obscure"],1],
    ["arduous","艰巨的；费力的",["demanding","laborious"],1],["artless","朴实的；不做作的",["guileless","unsophisticated"],2],["ascetic","苦行的；克己的",["austere","self-denying"],2],["assiduous","勤勉的；专心的",["diligent","sedulous"],1],["assuage","缓和；减轻",["alleviate","ease"],1],
    ["audacious","大胆的；鲁莽无畏的",["bold","daring"],1],["austere","朴素严厉的；简朴的",["severe","unadorned"],1],["avarice","贪婪；贪财",["greed","cupidity"],2],["belie","掩饰；与表象不符",["contradict","misrepresent"],1],["bolster","支持；增强",["support","strengthen"],1],
    ["capricious","反复无常的",["fickle","unpredictable"],1],["censure","严厉批评；谴责",["condemn","reprimand"],1],["circumspect","谨慎周到的",["cautious","prudent"],1],["cogent","有说服力的；有力的",["convincing","compelling"],1],["concede","承认；让步",["admit","yield"],1],
    ["conundrum","难题；谜题",["puzzle","dilemma"],2],["corroborate","证实；佐证",["confirm","substantiate"],1],["credulous","轻信的",["gullible","trusting"],2],["cursory","草率的；匆忙的",["hasty","superficial"],1],["dearth","缺乏；稀少",["scarcity","paucity"],1],
    ["decorous","得体的；合宜的",["proper","seemly"],2],["deleterious","有害的",["harmful","detrimental"],1],["demur","表示异议；反对",["object","protest"],2],["denigrate","贬低；诋毁",["belittle","disparage"],1],["derivative","缺乏原创性的；派生的",["unoriginal","secondary"],1],
    ["didactic","说教的；教学性的",["instructive","moralizing"],2],["diffident","缺乏自信的；羞怯的",["shy","self-doubting"],2],["disparate","截然不同的",["dissimilar","distinct"],1],["dogmatic","教条的；武断的",["doctrinaire","unyielding"],1],["eclectic","兼收并蓄的；折衷的",["diverse","wide-ranging"],1],
    ["enervate","使虚弱；削弱",["weaken","debilitate"],2],["engender","引起；产生",["cause","generate"],1],["enigmatic","神秘难解的",["puzzling","mysterious"],1],["ephemeral","短暂的；转瞬即逝的",["fleeting","transient"],1],["equanimity","镇定；平静",["composure","calmness"],2],
    ["equivocate","含糊其辞；闪烁其词",["prevaricate","hedge"],1],["erudite","博学的",["learned","scholarly"],1],["esoteric","深奥的；仅少数人懂的",["arcane","specialized"],1],["exacerbate","使恶化；加剧",["aggravate","worsen"],1],["exculpate","开脱；证明无罪",["absolve","exonerate"],2],
    ["fastidious","挑剔的；一丝不苟的",["meticulous","fussy"],1],["fortuitous","偶然发生的；幸运偶然的",["accidental","chance"],2],["garrulous","话多的；喋喋不休的",["talkative","loquacious"],1],["germane","相关的；贴切的",["relevant","pertinent"],1],["hackneyed","陈腐的；老生常谈的",["trite","cliched"],1],
    ["iconoclast","反传统者；挑战权威者",["nonconformist","rebel"],2],["impecunious","贫困的；身无分文的",["poor","penniless"],3],["inchoate","尚未成形的；初步的",["undeveloped","incipient"],2],["inimical","有害的；敌对的",["hostile","adverse"],2],["insipid","乏味的；淡而无味的",["dull","bland"],1],
    ["intransigent","不妥协的；顽固的",["uncompromising","obstinate"],1],["laconic","简洁寡言的",["terse","succinct"],1],["laud","赞扬；称颂",["praise","commend"],1],["mendacious","不诚实的；撒谎的",["dishonest","untruthful"],2],["mitigate","缓和；减轻",["alleviate","moderate"],1],
    ["obdurate","顽固的；冷硬的",["stubborn","unyielding"],2],["obsequious","谄媚的；卑躬屈膝的",["servile","sycophantic"],1],["opaque","不透明的；难懂的",["obscure","impenetrable"],1],["ostentatious","炫耀的；浮夸的",["showy","pretentious"],1],["parsimonious","吝啬的；过度节俭的",["miserly","stingy"],1],
    ["pedantic","卖弄学问的；过分拘泥细节的",["bookish","overly precise"],2],["perfunctory","敷衍的；草率的",["superficial","routine"],1],["placate","安抚；使平静",["appease","pacify"],1],["pragmatic","务实的；实际的",["practical","realistic"],1],["prolific","多产的；丰富的",["productive","abundant"],1],
    ["recalcitrant","抗拒权威的；难管理的",["defiant","uncooperative"],2],["recondite","深奥难懂的",["obscure","arcane"],2],["repudiate","拒绝接受；否认；抛弃",["reject","disown"],1],["sagacious","睿智的；有洞察力的",["wise","shrewd"],1],["sanguine","乐观的；充满信心的",["optimistic","confident"],1],
    ["spurious","虚假的；伪造的",["false","bogus"],1],["taciturn","沉默寡言的",["reserved","reticent"],1],["trenchant","犀利的；深刻有力的",["incisive","penetrating"],1],["ubiquitous","无处不在的",["omnipresent","widespread"],1],["vacillate","犹豫不决；摇摆",["waver","fluctuate"],1]
  ];
  const words = rawWords.map((x,i)=>({id:`v${i+1}`,word:x[0],cn:x[1],syn:x[2],level:x[3],pos:"",deck:"vocab"}));

  const verbal = [
    {id:"tc1",type:"Text Completion",prompt:"Because the committee had been criticized for secrecy, its chair made an unusually ____ effort to publish minutes and supporting data.",options:["cursory","transparent","capricious","esoteric","perfunctory"],answer:[1],explain:"The contrast with secrecy requires a word meaning open/clear: transparent."},
    {id:"tc2",type:"Text Completion",prompt:"The biographer is neither reverential nor hostile; her account is notable for its ____ tone, praising the scientist when warranted and criticizing him when necessary.",options:["equivocal","balanced","obsequious","acerbic","dogmatic"],answer:[1],explain:"The sentence describes evenhanded praise and criticism, so balanced fits."},
    {id:"tc3",type:"Text Completion",prompt:"Far from being a minor correction, the new evidence may ____ the prevailing theory by exposing a contradiction at its core.",options:["bolster","repudiate","corroborate","appease","laud"],answer:[1],explain:"A contradiction at the core would undermine/reject the prevailing theory; repudiate is the best fit."},
    {id:"se1",type:"Sentence Equivalence",prompt:"Although the lecturer was famous for elaborate digressions, today her explanation was remarkably ____.",options:["laconic","verbose","succinct","opaque","ornate","tortuous"],answer:[0,2],explain:"laconic and succinct both mean brief/concise and produce equivalent sentences."},
    {id:"se2",type:"Sentence Equivalence",prompt:"The mayor's promise sounded generous, but critics called it ____ because no funds had actually been allocated.",options:["cogent","specious","spurious","pragmatic","sagacious","salutary"],answer:[1,2],explain:"specious and spurious can both convey something deceptively plausible or false in this context."},
    {id:"se3",type:"Sentence Equivalence",prompt:"The editor rejected the phrase as ____: it had appeared so often that it no longer conveyed a fresh idea.",options:["hackneyed","novel","trite","trenchant","arcane","cogent"],answer:[0,2],explain:"hackneyed and trite both mean overused and unoriginal."},
    {id:"rc1",type:"Reading Comprehension",passage:"Early studies of urban heat treated cities as nearly uniform surfaces. More recent work, however, shows that temperature can vary sharply within a few blocks because tree cover, building materials, and traffic density differ. Thus citywide averages may conceal the neighborhoods at greatest risk during heat waves.",prompt:"The passage is primarily concerned with",options:["arguing that heat waves are becoming less predictable","showing why local variation can make citywide averages misleading","claiming that traffic density is the main cause of urban heat","describing a method for measuring tree cover","questioning whether cities are warmer than rural areas"],answer:[1],explain:"The central point is that neighborhood-level variation can be hidden by citywide averages."},
    {id:"rc2",type:"Reading Comprehension",passage:"Early studies of urban heat treated cities as nearly uniform surfaces. More recent work, however, shows that temperature can vary sharply within a few blocks because tree cover, building materials, and traffic density differ. Thus citywide averages may conceal the neighborhoods at greatest risk during heat waves.",prompt:"The author would most likely agree that",options:["a single citywide temperature measure may be inadequate for targeting interventions","tree cover always matters more than building materials","urban heat can be eliminated by reducing traffic","earlier studies intentionally ignored vulnerable neighborhoods","neighborhood measurements are unnecessary when citywide averages are available"],answer:[0],explain:"The passage explicitly warns that citywide averages can conceal high-risk neighborhoods."},
    {id:"rc3",type:"Reading Comprehension",passage:"Some historians once interpreted the spread of printing as an abrupt replacement of oral culture by print culture. Yet surviving records show that printed texts were often read aloud in homes, workshops, and taverns. Print therefore did not simply displace oral practices; it also supplied new material for them.",prompt:"Which statement best captures the author's view?",options:["Printing immediately ended most oral practices","Oral culture survived only where printed books were scarce","Printing and oral practices could reinforce one another","Historians lack enough evidence to study reading practices","Printed texts were rarely read privately"],answer:[2],explain:"The passage argues against simple replacement and says print supplied material for oral practices."},
    {id:"rc4",type:"Reading Comprehension",passage:"A drug that lowers a biomarker is not necessarily improving health. Some biomarkers are merely correlated with disease, while others play a causal role. Without evidence about the mechanism, treating the biomarker itself may change the measurement without changing the underlying outcome.",prompt:"The passage implies that a useful treatment evaluation should",options:["ignore biomarkers entirely","distinguish correlation from causation","favor treatments with the largest numerical biomarker change","assume that all biomarkers are causal","avoid studying biological mechanisms"],answer:[1],explain:"The author stresses that correlation and causation must be distinguished."}
  ];

  const quant = [
    {id:"q1",type:"Quantitative Comparison",prompt:"x is a positive number and x² = 49.\nQuantity A: x\nQuantity B: 7",options:["A is greater","B is greater","The quantities are equal","Cannot be determined"],answer:[2],explain:"Because x is positive and x²=49, x=7."},
    {id:"q2",type:"Quantitative Comparison",prompt:"n is an integer.\nQuantity A: n(n+1)\nQuantity B: 0",options:["A is greater","B is greater","The quantities are equal","Cannot be determined"],answer:[3],explain:"For n=1, A=2; for n=0 or -1, A=0. The relation is not fixed."},
    {id:"q3",type:"Single Choice",prompt:"A jacket is discounted by 20% and then the discounted price is increased by 25%. Compared with the original price, the final price is",options:["5% lower","the same","5% higher","10% higher","20% higher"],answer:[1],explain:"0.80 × 1.25 = 1.00, so the final price equals the original."},
    {id:"q4",type:"Single Choice",prompt:"The average of 5 numbers is 18. If one of the numbers, 22, is removed, what is the average of the remaining 4 numbers?",options:["16","17","17.5","18","19"],answer:[1],explain:"Total=90. Remove 22 gives 68; 68/4=17."},
    {id:"q5",type:"Multiple Select",prompt:"Which of the following numbers are divisible by both 6 and 8? Select all that apply.",options:["24","36","48","72","96"],answer:[0,2,3,4],explain:"A number divisible by both 6 and 8 must be divisible by lcm(6,8)=24."},
    {id:"q6",type:"Numeric Entry",prompt:"If 3x + 5 = 26, enter the value of x.",numeric:7,answerText:"7",explain:"3x=21, so x=7."},
    {id:"q7",type:"Single Choice",prompt:"A circle has radius 6. What is its area?",options:["6π","12π","18π","24π","36π"],answer:[4],explain:"Area=πr²=36π."},
    {id:"q8",type:"Single Choice",prompt:"A fair six-sided die is rolled twice. What is the probability that both rolls are even?",options:["1/6","1/4","1/3","1/2","3/4"],answer:[1],explain:"P(even)=3/6=1/2 each roll; independent probability=(1/2)²=1/4."},
    {id:"q9",type:"Quantitative Comparison",prompt:"a and b are positive and a > b.\nQuantity A: a/b\nQuantity B: 1",options:["A is greater","B is greater","The quantities are equal","Cannot be determined"],answer:[0],explain:"With positive a>b, dividing by positive b gives a/b>1."},
    {id:"q10",type:"Single Choice",prompt:"A data set is 2, 4, 4, 7, 8. Which statement is true?",options:["Mean = median","Mean < median","Mean > median","Range = 5","Mode = 7"],answer:[0],explain:"Mean=25/5=5 and median=4? Wait: sorted median=4, so mean>median. Correct answer is Mean > median."},
    {id:"q11",type:"Single Choice",prompt:"If y = 2x - 3 and x = 5, what is y?",options:["5","7","8","10","13"],answer:[1],explain:"y=2(5)-3=7."},
    {id:"q12",type:"Multiple Select",prompt:"For which values of x is x² < 9? Select all that apply.",options:["-4","-2","0","2","4"],answer:[1,2,3],explain:"x²<9 means -3<x<3."}
  ];

  const issues = [
    {prompt:"Universities should require all graduate students to take at least one course outside their primary field of study.",instruction:"Discuss the extent to which you agree or disagree. In developing your position, consider circumstances in which the recommendation would or would not be beneficial."},
    {prompt:"Governments should prioritize policies whose benefits can be measured within a few years rather than policies whose main benefits may take decades to appear.",instruction:"Discuss the extent to which you agree or disagree, considering possible consequences of adopting the claim."},
    {prompt:"The most effective way to encourage innovation is to tolerate a substantial amount of failure.",instruction:"Discuss the extent to which you agree or disagree and support your position with reasons and examples."},
    {prompt:"Experts are most useful to society when they communicate uncertainty as clearly as they communicate conclusions.",instruction:"Discuss the extent to which you agree or disagree, considering situations in which uncertainty should receive more or less emphasis."},
    {prompt:"Educational institutions should evaluate students more on long-term projects than on timed examinations.",instruction:"Discuss the extent to which you agree or disagree and explain the conditions under which each form of evaluation is useful."},
    {prompt:"Society benefits more from people who question established practices than from people who perfect those practices.",instruction:"Discuss the extent to which you agree or disagree, considering both innovation and reliability."}
  ];

  return {words,verbal,quant,issues,meta:{version:"0.1.0",vocabNote:"GRE-oriented starter deck; not an official ETS word list",practiceNote:"All practice questions are original and are not ETS questions."}};
})();